name: attendance_system
description: "Smart Attendance System with QR Code Scanner"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.66.2
  provider: ^6.1.1
  mobile_scanner: ^3.5.7
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
